global using Microsoft.AspNetCore.Builder;
global using Microsoft.Extensions.DependencyInjection;
global using AntDesign.ProLayout;
global using Microsoft.AspNetCore.Components;
global using Microsoft.Extensions.Hosting;
global using AntDesign;
global using System;
global using System.Net.Http;
global using System.Collections.Generic;
global using WeComLoad.Admin.Blazor.Models;
global using System.Net.Http.Json;
global using Newtonsoft.Json;
global using System.Threading.Tasks;
global using WeComLoad.Admin.Blazor.Utils;
global using Microsoft.AspNetCore.Hosting;
global using System.IO;
global using WeComLoad.Shared;
global using System.Linq;
global using static WeComLoad.Shared.Model.WeComSuiteAppAuthDetail;
global using WeComLoad.Shared.Model;
global using WeComLoad.Admin.Blazor.Services;
global using Microsoft.AspNetCore.Components.Web;
global using WeComLoad.Admin.Blazor.Extensions;

